Vagrantfile, ansible/group_vars/all, ansible/roles/ceph-common/defaults/main.yml, ansible/roles/ceph-common/tasks/install_on_redhat.yml, ansible/roles/ceph-radosgw/templates/ceph-extra.repo
This provides a number of fixes to the build to make it more reliable. In particular, the RPM that ceph uses to install its repository data relies on a URL for the GPG key which is not always available. We try to provide multiple solutions here to resolve the problem.
=> Fix ceph ansible

cephdriver/cephdriver_test.go, cephdriver/volume.go, config/volume.go, docs/4_configuration.md, systemtests/integrated_test.go, volplugin/cgroup.go, volplugin/handlers.go
This implements rate limiting. It comes in three distinct parts:
* config -- parameters, json configuration
* cephdriver -- code to gather device major/minor numbers and report it (and other critical data) with the mount.
* volplugin -- code to implement the cgroups file writes to the blkio controller on mount.
the blkio directives we're utilizing automatically vaporize on a umount, which is what we do any time the container is stopped. Therefore, applying them each time becomes idempotent, even with multiple hosts and mounts going on at the same time.
The tests verify the files are written to with magic numbers; they are high enough in value that they allow the fsck to proceed. :)
the major/minor device number code is pretty linux specific, and probably bad.
=> Rate limit io

Makefile
This PR changes the Makefile targets slightly. These changes have lowered the execution time of the unit-test target from 39 seconds to 30 seconds on my machine.
=> Makefile: optimize unit-test & run-build targets

Makefile
This PR is an attempt to speed up reflex-unit-test a bit. `unit-test` takes ~45 seconds on my system right now. `unit-test-nocoverage` takes only 25 seconds.
=> Makefile: use nocoverage for reflex unit-test

Makefile, config/use.go, config/use_test.go, storage/backend/ceph/mountscan.go, systemtests/integrated_test.go, systemtests/util_test.go, volmaster/daemon.go, volmaster/volmaster/cli.go, volplugin/handlers.go, volplugin/utils.go, volplugin/volplugin.go, volplugin/volplugin/cli.go
@mapuri @unclejack @jainvipin 
This implements TTL support or crash-resistant recovery from #76. It implements this by using etcd TTL support to automatically expire records when the host does not report back.
The host may re-acquire the lock on volplugin restart if if the lock has not be re-acquired.
The third case where volplugin is not restarted (therefore the locks are not refreshed) and the mounts are not cleared, this will be settled by another PR which will introduce a "maintenance mode" that people can run to perform host operations without being able to acquire mounts and whatnot. This allows people to keep the locks in place while performing maintenance.
This is a large, critical change so please PTAL (all of you) and review carefully. @shaleman I know you don't work on this …
=> config,volmaster,volplugin: first pass at TTL support

config/config.go, config/tenant.go, config/tenant_test.go, config/use_test.go, config/util_test.go, config/volume.go, config/volume_test.go, systemtests/volcli_test.go
These tests push the tests for `config` into the 80+ percentile for coverage. The outliers are marshal calls (hard to test and somewhat pointless) and some output validation routines that were particularly hard to trigger due to how things are done in volplugin.
Note that the tests will not pass right now; when @mapuri's ansible etcd changes can be integrated it will pass.
=> More tests

Godeps/Godeps.json, Godeps/_workspace/src/github.com/contiv/vagrantssh/.gitignore, Godeps/_workspace/src/github.com/contiv/vagrantssh/Makefile, Godeps/_workspace/src/github.com/contiv/vagrantssh/testbed.go, Godeps/_workspace/src/github.com/contiv/vagrantssh/vagrantnode.go, Vagrantfile, systemtests/battery_test.go, systemtests/init_test.go, systemtests/integrated_test.go, systemtests/util_test.go, systemtests/volcli_test.go, systemtests/volplugin_test.go, systemtests/volume_test.go, vagrant_variables.yml
This adds two new battery tests that exercise parallel operations on the system. 
They're don't work very hard because vagrantssh still doesn't scale beyond ~20 connections, need to figure out what's wrong with the sshd config which has to be the issue at this point.
=> More systemtests

Godeps/Godeps.json, Godeps/_workspace/src/github.com/contiv/vagrantssh/Makefile, Godeps/_workspace/src/github.com/contiv/vagrantssh/Vagrantfile, Godeps/_workspace/src/github.com/contiv/vagrantssh/baremetal.go, Godeps/_workspace/src/github.com/contiv/vagrantssh/sshnode.go, Godeps/_workspace/src/github.com/contiv/vagrantssh/testbed.go, Godeps/_workspace/src/github.com/contiv/vagrantssh/vagrant.go, Vagrantfile
This upgrades github.com/contiv/vagrantssh to vendor in the new 1.8 fixes. It also brings in a critical `Vagrantfile` change for 1.8.
=> Upgrade vagrantssh

README.md
`make run` will run both the volplugin and volmaster on all the hosts. so, the statement about "starting volplugin" manually is not necessary.
make start will fail if https_proxy is specified. so, adding a note for not using https_proxy as ansible does not support.
=> minor corrections in readme

Vagrantfile
This fixes vmware on OSX. Since this is not tested in our current matrix and I know it works, I am going to merge immediately.
=> Vagrantfile: quote arguments to vmware-vdiskmanager (because of the spaces in the path)

.dockerignore, Dockerfile, Makefile
This allows docker images to be built and pushed to the hub.
=> Dockerfile,.dockerignore,Makefile: docker image support

executor/executor.go, executor/executor_test.go, storage/backend/ceph/ceph.go, storage/backend/ceph/internals.go, storage/backend/ceph/mountscan.go, storage/backend/ceph/util.go
This principally affects the ceph driver but it implements (see first commit) a new package called `executor` which is a supervising and interruptible... a wrapper for exec.Cmd structs.
The second commit is the integration into the ceph driver. It does not do anything with hard timeouts yet, but we have a few other steps that need to be taken before we can start leveraging that feature.
=> Unified exec pipeline

Makefile, contrib/completion/bash/volcli
(1) Bash autocompletion file for volcli
(2) change to package this file in the tar
note: the ansible changes for copying the volcli file to /etc/bash_completion.d/ need to be done. They  will be done after the Makefile change is merged, as a tar with the changes is required to deploy.
for now, to test these changes one needs to,
sudo cp contrib/completion/bash/volcli /etc/bash_completion.d/
source /etc/bash_completion.d/volcli
```
[vagrant@mon0 volplugin]$ volcli
help    tenant  use     volume
[vagrant@mon0 volplugin]$ volcli tenant
delete  get     help    list    upload
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli tenant get tenant
tenant1  tenant2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli tenant delete tenant
tenant1  tenant2
[vagrant@mon0 volplugin]$ …
```
=> Bash autocomplete for volcli

ansible/roles/docker/templates/docker-svc.j2
Merging as soon as tests pass.
This cuts runtime for tests in half.
=> ansible/roles/docker: use overlayfs storage backend.

systemtests/volplugin_test.go, volplugin/volplugin.go
/cc @shaleman @vvb 
This fixes fd leaks caused by API hyperactivity in docker 1.10.
=> volplugin,systemtests: ensure no FDs are carried by keepalive connections over the unix socket.

Vagrantfile, storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go, storage/backend/ceph/internals.go, systemtests/battery_test.go, systemtests/util_test.go
This *removes* RBD locking and instead relies on our etcd locking strategy. RBD locks were in some situations unremovable, so I figured this was the best solution for now.
This also brings a few more enhancements to the tests while debugging this, and an upgrade to docker 1.10.1 in the ansible.
=> Stability enhancements

Makefile
the new FD test times out on jenkins. I'm going to merge this immediately so it does not break the rest of our tests.
=> Makefile: increase unit test time to 240m

storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go, storage/driver.go, volmaster/volume.go, volplugin/handlers.go, volplugin/utils.go
These patches push the management of metacharacters other than `/` down to the storage driver so they can deal with it.
fixes #75
=> Metacharacter management

.gitignore, config/global.go, config/global_test.go, config/policy.go, config/volume.go, storage/backend/backends.go, storage/backend/ceph/ceph.go, storage/backend/null/null.go, storage/driver.go, systemtests/init_test.go, systemtests/testdata/nulldriver.json, systemtests/util_test.go, systemtests/volcli_test.go, systemtests/volmaster_test.go, volcli/commands.go, volcli/volcli.go, volcli/volcli_test.go, volmaster/daemon.go, volmaster/volume.go, volplugin/handlers.go, volplugin/volplugin.go, volsupervisor/snapshots.go
The changes here introduce a null driver that basically doesn't perform any actual disk operations.
The driver to use for a volume is set in `volume-options` using field called `backend`. The default backend is `ceph` and a user can override it by specifying the `backend` field in `default-options` structure.
The primary use case of the null driver will be to use it in scale/battery tests to exercise/benchmark volplugin alone  and I plan to work on that next. But I put out this PR to make sure I am working in right direction and also to keep the patch small.
fixes #153 
@erikh @unclejack PTAL
=> Add a null/no-op volume driver

config/global.go, config/global_test.go, lock/client/client.go, storage/backend/backends.go, storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go, storage/backend/ceph/util.go, storage/backend/null/null.go, storage/driver.go, systemtests/testdata/mountpath_global.json, systemtests/volplugin_test.go, volmaster/daemon.go, volmaster/volume.go, volplugin/handlers.go, volplugin/volplugin.go, volsupervisor/snapshots.go
This provides the base mount point (hard-coded as a default previously as `/mnt/ceph`) as a configurable global.
I made some tests but I'm sorry for the size of this patch; it just touched everything.
Be aware this also depends on the #170 patch getting merged first.
=> Mountpoint global

systemtests/volplugin_test.go, volplugin/volplugin.go
this makes volplugin wait unitl the volmaster starts to attempt doing anything else. it logs the result of whether or not it contacted its volmaster.
depends on #171 and #147 being merged first. check the last commit for the meat.
@mapuri @unclejack
=> volplugin,systemtests: ensure resiliency when the volmaster goes down and volplugin is starting.

config/config.go, executor/executor.go, lock/lock.go, storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go, storage/backend/null/null.go, storage/driver.go, systemtests/integrated_test.go, systemtests/testdata/fastsnap.json, systemtests/volsupervisor_test.go, volcli/commands.go, volcli/volcli.go, volmaster/daemon.go, volsupervisor/loop.go
This implements `volcli volume snapshot` commands:
* `volcli volume snapshot list` will list all snapshots for a given volume
* `volcli volume snapshot copy` will copy a snapshot from volume A into new volume B (under the same policy)
Please take a close look here as a lot has changed.
/cc @jainvipin @mapuri @unclejack
=> Volume snapshot copy

ansible/roles/contiv_cluster/defaults/main.yml, ansible/roles/contiv_cluster/tasks/main.yml, ansible/roles/swarm/tasks/main.yml
collins and swarm are large container images that we save during the build
process; however, no attempt to determine if the image is already installed is
made before pulling it, causing an expensive web hit at best and a fresh
download of a version we don't want at worst.
=> Collins fix

systemtests/volsupervisor_test.go
This increases a sleep in the TestVolsupervisorRestart system test to ensure reliability.
=> Increase sleep

Vagrantfile
This speeds up the VM provisioning through the use of linked clones for the VMs. This lowers the time required to create each VM from 20-50 seconds down to one second or less.
=> Vagrantfile: use linked clones on VirtualBox

config/config.go, config/policy.go, storage/backend/backends.go, storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go, storage/backend/ceph/internals.go, storage/backend/ceph/util.go, storage/backend/nfs/nfs.go, storage/backend/null/null.go, storage/driver.go, systemtests/init_test.go, systemtests/testdata/ceph/global-fasttimeout.json, systemtests/testdata/ceph/global1.json, systemtests/testdata/ceph/global2.json, systemtests/testdata/ceph/mountpath_global.json, volmaster/daemon.go, volmaster/volume.go, volplugin/handlers.go, volplugin/utils.go, volplugin/volplugin.go, volsupervisor/loop.go
This provides an implementation of a stub NFS driver + a revisitation of storage drivers in general.
Drivers are now split into Mount, Snapshot, and CRUD (Create/Retrieve/Update/Delete) drivers. Each driver has its own unique sets of methods (except for Name, which is shared through `storage.NamedDriver`) that do not overlap. To operate with a driver, you use the `backend` library to take it, then perform operations on it based on the standard interfaces.
Now, drivers do not have to provide functionality for every subsystem, just the ones they support. Future patches will implement this integration as we get more storage capabilities.
=> Restructure storage drivers

config/global.go, config/global_test.go, config/policy.go, storage/backend/backends.go, storage/backend/null/null.go, systemtests/testdata/ceph/global-fasttimeout.json, systemtests/testdata/ceph/global1.json, systemtests/testdata/ceph/global2.json, systemtests/testdata/ceph/mountpath_global.json, systemtests/testdata/test/global1.json, systemtests/util_test.go, systemtests/volcli_test.go, volcli/volcli.go, volmaster/daemon.go, volmaster/volume.go, volplugin/utils.go
This implements a null (that is, no operations at all) driver suitable for use in production. it will be the foundation of the lack of a CRUD or snapshot system for NFS operations.
This also makes the backend dependent now on the volume instead of the global, which was removed. This is the next step towards multiple backends.
=> Null driver

Vagrantfile
This bumps Docker to 1.11.1. I've run the tests and it's all passing.
=> Vagrantfile: bump Docker to 1.11.1

Makefile, config/merge_test.go, config/policy.go, config/volume.go, lock/lock.go, systemtests/battery_test.go, systemtests/init_test.go, systemtests/testdata/nfs/unlocked.json, systemtests/volplugin_test.go, volplugin/handlers.go, volplugin/volplugin.go
This patch implements lock free operation as a toggle. What it does internally is replace the hostname for the exclusive lock on mount to a static string; this way any host can "take" the lock, but it still prevents mounted volumes from existing after a Remove call is issued (it will fail if there are any mounted).
It's not quite ready; there are still some tests to write and some cleanups to do. I was hoping for a preliminary review + CI pass before I move further, as the necessary code is here already.
@mapuri @unclejack @dseevr
=> Lock free operation

Makefile, volcli/volcli/cli.go, volmaster/volmaster/cli.go, volplugin/volplugin/cli.go, volsupervisor/volsupervisor/main.go
this let's us pass the version string from release CI to the built binaries thereby tying the binaries downloaded from github to respective releases.
Also it enables us to push versioned volplugin container images (with every github release) that we can use for setting up volplugin in our ansible. This will be done is a subsequent PR.
/cc @erikh @dseevr @unclejack
=> add version support in build target

config/config.go, config/config_test.go, info/debug.go, volmaster/daemon.go
I believe this satisfies all the requirements in #247 
mkstemp is not necessary because ioutil.TempFile implements similar logic using O_EXCL.
=> config,volmaster: volmaster handles SIGUSR2 and dumps a gzipped tarball of volplugin's etcd keys

config/config.go, config/volume.go, config/volume_test.go, lock/lock_test.go, volcli/commands.go, volcli/volcli.go, volmaster/daemon.go, volplugin/utils.go
This makes the API considerably simpler by making most requests use the same structure. Additionally, I have lower-cased all properties so they are easier to use.
Fixes #298
=> *: Remove config.RequestCreate; normalize with config.Request

Makefile, build/scripts/systemtests.sh, errors/errors.go, storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go, storage/backend/ceph/internals.go, systemtests/integrated_test.go, volmaster/daemon.go
* We failed to acquire a lock when the volume was mounted, which timed out preventing the copy and a lengthy round trip on the error. The code was adjusted to remove the requirement that the volume would not be mounted.
* Several bugs in the ceph storage driver around copying were fixed:
* when EBUSY is returned during a snapshot volume protect, *do not* fail. It is simply because the snapshot  is already protected.
* when EEXIST is returned during any copy operation, the volume named would be cleaned up as a part of the healing process, which would in turn remove the volume if it exists. Previously, this would clean up any named volume.
Fixes #294 /cc @vishal-j
=> Several issues with copying snapshots

Makefile, systemtests/init_test.go, volplugin/handlers.go, volplugin/mountcount.go
This fixes a bug in the mount counting code that would cause it to go negative. You would have to acquire volumes very fast on multiple hosts and then it to happen, which is a significant edge case.
To prevent future bugs in the future like this, I have added some code to panic the daemon if the mount count goes negative. We can do serious damage if we don't, as the counting system gets off and duplicate maps/mounts happen.
=> Fixes for same-host multi-mount mode

Makefile, volplugin/handlers.go, volplugin/volplugin.go
This implements the necessary API calls to present ourselves as a global driver to docker.
Necessary in Swarm 1.1 and up, and docker 1.12.
=> Global driver

.gitignore, Makefile, Vagrantfile, vagrant_variables.yml
Octet reservation is protected by locking so it’s safe to bring up many environments at the same time.
Addresses #319
=> Vagrantfile: randomize the third octet of the subnet to allow for up to 255 development environments

storage/driver.go
=> storage/driver.go: removed specific references to ceph in generic error messages

lock/lock.go, systemtests/apiserver_test.go, systemtests/battery_test.go, systemtests/integrated_test.go, systemtests/util_test.go, systemtests/volcli_test.go, systemtests/volplugin_test.go, systemtests/volsupervisor_test.go, systemtests/volume_test.go
The volume CRUD primitives were lousy. I moved on @mapuri's randomized
containers patches and did the same for volumes. Because of a bug in docker
(see below) we cannot create the same volume twice in a short period of time
without hitting a cache bug:
docker/docker#24205 for more information.
This fix implements a cleaner API for managing volumes, and converts the whole
suite to use those features, including the randomized volume names.
=> Improve test performance

apiserver/daemon.go, config/global.go, config/global_test.go, systemtests/volcli_test.go
Globals were pretty ugly in how they calculated parameters. They were stateful
and it was hard to manage between the different spots in the code.
I refactored it to use a stateless design with three new functions to set
parameters in a functional way. This way instead of passing around mutable
state, code can just ask for the type of parameters it needs.
Fixes #334 
/cc @melanietom 
=> apiserver,config: refactor Global configuration management (see below)

Makefile, Vagrantfile
This was one of the blockers for `vagrant reload` working successfully. https://github.com/contiv/volplugin/issues/332
The other was the kernel being upgraded by Ansible resulting in the vbox drivers not being loaded after reboot, which broke shared folders.  This was addressed by @mapuri here: https://github.com/contiv/ansible/pull/245
cc @erikh
=> Vagrantfile: skip creating vbox disk image if it already exists

Makefile
This flag should have been added in #346.
See:  https://github.com/contiv/volplugin/issues/332#issuecomment-233085163
Thanks, @mapuri!
=> Makefile: add --provision flag to 'reload' target to ensure services are started after VM reboot

README.md, config/volume.go, config/volume_test.go, systemtests/init_test.go, systemtests/integrated_test.go, systemtests/testdata/iops1.json, systemtests/util_test.go, systemtests/volplugin_test.go, volplugin/cgroup.go
This removes IOPS controls; we could not guarantee these values for either Ceph or NFS. The BPS rate limiting for Ceph is still applied, and as soon as I can figure out what I need to do with `tc` to handle the NFS side, I will.
Opinions on the change are encouraged. /cc @mapuri @jainvipin
=> README.md,config,systemtests,volplugin: remove IOPS controls.

build/scripts/systemtests.sh
- remove the loop otherwise the tests run twice adding to test time
- also remove setting GOPATH for the CI environment in scripts, it is better to control it from higher level jenkins job or make target
I found some of these while trying out parallel tests.
/cc @erikh
=> build/scripts: fix systemtest logic

Makefile
This will help cleanup state on CI machines, once the job has completed. It will be useful otherwise too I think.
/cc @dseevr @erikh
=> Makefile: clean up global state associated with the vagrant setup

storage/backend/ceph/ceph.go, storage/backend/ceph/ceph_test.go
Ceph's pool/image syntax is now used. This corrects many errors taking snapshots from alternative pools, which previously attempt to use `--pool` which unfortunately is not supported for some snapshot operations. The pool syntax has been unified in the call to mkpool().
Fixes #362
=> Fix multi pool snapshots

apiserver/daemon.go, config/archive.go, config/archive_test.go, config/config.go, config/policy.go, errors/errors.go, volcli/commands.go, volcli/volcli.go, volcli/volcli_test.go
- Get all revision numbers: `volcli policy history list $name`
- Retrieve the policy text for a specific revision: `volcli policy history get $name $revision`
- Watch for new policies being uploaded: `volcli policy watch`
Fixes #269
=> apiserver,config,errors,volcli: add volcli commands to get, list, and watch policy revision changes

Vagrantfile
This PR works around some of the VMM bugs discovered in VirtualBox 5.0.x and fixed in 5.1.x.
=> Vagrantfile: disable GRO on VirtualBox

api/handlers.go
A number of things changed:
* Use locks are *never* taken in unlock mode. This corrected a number of
potential (but unproven) races when switching between the two modes.
Locked/unlocked can theoretically be runtime now.
* Order of operations:
* TTL refresh is garbage collected
* the long-term use lock is taken
* the mount counter is checked
* mount occurs
* then the TTL refresh is restarted
* This corrects situations where the TTL refresh would trump the permanent lock
=> api: fix some issues with the lock handler. See below.

Dockerfile.autorun
Since `Dockerfile.autorun` always pulls the latest docker version, we get into API incompatibility issues. So, fixing the docker version in the Dockerfile. 
```
Aug 04 06:43:28 mon0 volplugin.sh[25990]: + docker run --net host --name volplugin --privileged -i -d -v /dev:/dev -v /lib/modules:/lib/modules:ro -v /var/run/docker...
Aug 04 06:43:28 mon0 volplugin.sh[25990]: docker: Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23).
Aug 04 06:43:28 mon0 volplugin.sh[25990]: See 'docker run --help'.
```
=> fix docker version for volplugin-* container build

build/scripts/apiserver.sh, build/scripts/contiv-vol-run.sh, build/scripts/volplugin.sh, build/scripts/volsupervisor.sh
`systemctl stop volplugin/volsupervisor/apiserver` now stops the container and does not remove it. when a `systemctl start` is issued, the same container is started again. a `rm` target is also added to `volplugin.sh/volsupervisor.sh/apiserver.sh` which will optionally remove the containers too.
=> build: restart stopped containers instead of new ones

Makefile, volmigrate/backend/backend.go, volmigrate/backend/etcd2/etcd2.go, volmigrate/commands.go, volmigrate/migration.go, volmigrate/schema_migrations.go, volmigrate/volmigrate.go, volmigrate/volmigrate/cli.go, volmigrate/volmigrate_test.go
Commands:
`volmigrate list`          -> see all migration versions and descriptions
`volmigrate run [version]` -> run all pending migrations up to [version]
`volmigrate run`           -> run all pending migrations
`volmigrate version`       -> see the local schema version (0 if no migrations have ever run)
The current schema version is held in the "/volplugin/schema-version" key.  Each migration will increment the version by 1 (i.e., the first migration is 1, the second is 2, and so on).  Migration numbers can't be reused.
There is an optional global --silent flag to suppress the confirmation prompt when attempting to run migrations.
Fixes #353
=> volmigrate, Makefile: add volmigrate tool which can list and run schema migrations

api/handlers.go, systemtests/util_test.go
This fixes an ordering issue in the locking code where a goroutine would dangle, or be left unchecked, refreshing a TTL on a lock that no longer needed to be held. Additionally, if the mount failed the lock would not be cleared.
I also fixed a small test issue with taking enough time to boot the API server.
=> Fix dangling ttl goroutine

Makefile, build/scripts/deps.sh, systemtests/util_test.go
We were hitting apiserver before it was ready to serve requests.
This PR uses `connwait` to wait for apiserver to be ready.
we also keep track of time it takes to become accessible.
=> build,systemtests: wait for apiserver to be reachable

build/scripts/build-volplugin-containers.sh
When doing a make run, we need to clean up earlier contiv/volplugin docker
image from the system. This also mandates that any containers using the
image are stopped and removed.
Additionally, repeatedly running `docker build` can lead to dangling images.
These are also cleaned.
=> build: ensure that new code runs in containers on make run

build/scripts/checks.sh
gofmt sometimes includes blank lines in its output, and those are now stripped out.
=> checks.sh: fix gofmt/golint/govet checks whose outputs were not being properly checked

apiserver/daemon.go, volcli/volcli.go
Fixes #413 
The snapshot copy api response was empty; the UI team would like it if it returned the volume that was created.
I have done this and also adjusted volcli to output the name of the new volume after copy.
=> Return volume at snapshot copy time

Makefile, build/scripts/build-volplugin-containers.sh, build/scripts/contiv-vol-run.sh, build/scripts/deps.sh, build/scripts/enable-private-registry.sh
Added `run-fast` and `run-registry` Makefile targets.
run-registry - creates a private registry and adds the necessary DOCKER_OPTS to
allow for an insecure-registry.
run-fast - build the changes on mon0, tags the images, and pushes it to private
registry on mon0. mon1 and mon2 pull this image from mon0's docker registry.
starts the processes as usual. cleans any dangling images that are left over.
conscious choices:
At multiple places the number of mon instances is fixed ($(seq 0 2)) in Makefile. Getting
this from `vagrant status` was taking time. Since, I am going to hack on this
further to see if some tasks can be parallelised. I will take care of this
hard-coding then.
=> Makefile, build: support for private registry for container images

systemtests/init_test.go, systemtests/util_test.go, systemtests/volplugin_test.go, systemtests/volume_test.go, volplugin/init.go, volplugin/volplugin.go, volplugin/volplugin/cli.go
This adds a flag to volplugin to change the socket name. This name is appended
to teh base plugins directory path and then suffixed with '.sock'. It will be
presented as the name provided in docker volume plugin listings, so it makes
for a nice UX.
Fixes #399
=> volplugin,systemtests: make socket (aka plugin) name variable.

Makefile
Will be quick-merging this if/when tests pass.
This (I think) fixes the issue with volcli global uploads not working on make restart or after etcd is terminated.
=> Makefile: wait for etcd on startup

Makefile
this fixes some rare `make run` terminations.
=> Makefile: use etcdctl cluster-health to determine when cluster is ready, instead of connwait.

Makefile, build/scripts/enable-private-registry.sh, build/scripts/run.sh
Moved the `run` and `run-fast` target logic to a single bash script.
Noticed that etcd cluster takes about 2 seconds to become healthy after a docker restart. Added the logic to `wait_for_etcd`.
=> Makefile, build: moving run target logic to a script

Makefile, Vagrantfile
Demo mode was a short-lived feature that ran only 1 VM. It was superceded by
run-in-containers. It is no longer needed.
Fixes #453
=> Makefile,Vagrantfile: remove demo mode

build/scripts/autorun-bootstrap.sh
The bug here is that if you use the autorun tools, the default policy and global weren't automatically uploaded. This does not line up with the documentation.
=> build/scripts/autorun-bootstrap.sh: restore policy and global upload into autorun container image
