contiv/volplugin

Vagrantfile
ansible/group_vars/all
ansible/site.yml
librbd/utils.go
vagrant_variables.yml

use centos71 as our base image

---

volmaster/schedule_utils.go
volmaster/snapshots.go

volmaster: move volume iteration code to a generic function

---

config/config_test.go
config/tenant.go
config/volume.go
config/volume_test.go
systemtests/integrated_test.go
systemtests/util_test.go
systemtests/volcli_test.go
volmaster/image.go
volplugin/handlers.go
volplugin/utils.go

thsi is a pretty sloppy patch, sorry.
closes #17

config,systemtests,volmaster,volplugin: namespace rbd volume names by tenant as well, providing an additional way to relate volumes to tenants.

---

Makefile
README.md
cephdriver/volume.go
docs/2_getting-started.md
docs/3_architecture.md
systemtests/integrated_test.go
systemtests/testdata/fastsnap.json
systemtests/util_test.go
volmaster/daemon.go
volsupervisor/daemon.go
volsupervisor/schedule_utils.go
volsupervisor/snapshots.go
volsupervisor/volsupervisor/cli.go

This partially resolves #16 and also means that the volmaster can now be used on multiple hosts at once (and is tested that way).

new volsupervisor binary replaces scheduled tasks in volmaster and makes volmaster multi-master.

---

systemtests/integrated_test.go

systemtests: remove test output from snapshot test

---

ansible/site.yml

ansible: upgrade golang inside vms

---

README.md

README.md: update supported features list

---

Makefile

This shall enable publishing the volplugin releases to github, similar to netplugin.
@erikh PTAL when you get a chance.

Makefile: add targets for posting volplugin release

---

Makefile
ansible/site.yml

Makefile,ansible: remove docker master build now that 1.9 is out.

---

Makefile
README.md

contains a few fixes to get the build green all the time.
merging.

Build fixes

---

volcli/commands.go
volcli/volcli.go
volmaster/volmaster/cli.go
volplugin/volplugin/cli.go
volsupervisor/volsupervisor/cli.go

see commit list, these are for integrating into github.com/contiv/contivctl which is a unified binary for volplugin and netplugin.

Contivctl changes

---

CONTRIBUTING.md

This PR brings some of the changes made to the same file on the netplugin repository.

contributing: add DCO section & small changes

---

README.md

README.md: update link to build status

---

README.md

README.md: update to point at new docs site

---

vagrant_variables.yml

Explicitly use version 0.3.1 until the boxes stabilize again.

---

vagrant_variables.yml

vagrant_variables.yml: upgrade centos71-netplugin box

---

vagrant_variables.yml

Revert "vagrant_variables.yml: upgrade centos71-netplugin box"

---

Makefile

Makefile: increase system test timeout to 30 minutes.

---

volplugin/handlers.go

This PR dedpuplicates some code in the volplugin handlers.

volplugin: deduplicate code in handlers

---

config/merge.go
storage/backend/ceph/ceph.go

This PR fixes a cosmetic issue with one error and fixes an issue related to returning an error in merge.

config,storage: fix unhandled errors

---

vagrant_variables.yml

vagrant_variables.yml: upgrade box to 0.5.0

---

.gitignore
Makefile

Makefile,.gitignore: coverage profiles on unit tests.

---

storage/backend/ceph/ceph.go
storage/backend/ceph/ceph_test.go
storage/driver.go

@unclejack @mapuri PTAL, this is important to another change I'm working on, but wanted to keep the review set simple.

storage: driver interface + ceph implementation of ShowMapped

---

volplugin/handlers.go

volplugin: fix a bug in handlers.go where the fully qualified path would be passed instead of just the volume name.

---

README.md

README.md: update the build status link

---

Makefile

Makefile: use variables to eliminate much repetitive text

---

README.md

UPdate the ngrok and docs urls. Insta-merging

Ngrok update

---

README.md

README.md: update again for build status link

---

storage/backend/ceph/ceph.go
storage/backend/ceph/ceph_test.go
storage/backend/ceph/mountscan.go
storage/driver.go

@unclejack @mapuri @jainvipin PTAL
closes #61

storage: rename ShowMapped to Mounted, gather mount points and other critical data from host.

---

README.md

README.md: update jenkins link for the last time

---

config/use_test.go

config: fix `gofmt -s` in use test

---

config/use.go

config: Remove a no-longer-accurate comment

---

ansible/roles/ceph-mon/tasks/ceph_keys.yml

This brings in https://github.com/contiv/ansible/pull/6

Ansible race

---

storage/backend/ceph/internals.go

On the distribution of Ceph I'm using, rbd outputs nothing when it maps. Using the showmapped command after the map returns gives the JSON result, which is iterated for the new device name.

Use the rbd showmapped command after mapping, as rbd outputs nothing.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/contiv/vagrantssh/vagrant.go
Makefile
Vagrantfile
ansible/roles/base/tasks/main.yml
vagrant_variables.yml

@mapuri @unclejack PTAL
Note that this requires the VMware fusion or workstation which is a for-pay addition by hashicorp.
The tests run significantly faster, and provisioning time is improved if you do use it. The networking is also marginally more sane. :)
Other patches have been submitted to the respective repositories so they can be added that way.

Vmware Support

---

Vagrantfile
ansible/roles/base/tasks/redhat_tasks.yml

Sorry for the vague description, but this fixes a number of build-related issues with volplugin that ... aren't related to volplugin itself.
The commit messages speak for themselves.

Fix a few things

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/contiv/systemtests-utils/.gitignore
Godeps/_workspace/src/github.com/contiv/systemtests-utils/system.go
systemtests/util_test.go

this speeds up test performance and increases reliability.

Pgrep wait startup

---

systemtests/testdata/fs.json
systemtests/volmaster_test.go
volmaster/daemon.go
volmaster/volume.go

Volmaster fix map race

---

Makefile
README.md

Makefile: sudo install ansible so it doesn't end up in $HOME/.local

---

config/use.go
config/volume.go
executor/executor.go
storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
storage/backend/ceph/mountscan.go
storage/driver.go
systemtests/battery_test.go
systemtests/integrated_test.go
systemtests/util_test.go
systemtests/volcli_test.go
systemtests/volplugin_test.go
systemtests/volume_test.go
volmaster/daemon.go
volplugin/handlers.go
volplugin/volplugin.go

This fixes docker 1.10 compatibility. It incorporates #129 and #127 which are already LGTM'd.
Please review immediately if you can; the build is broken without it. Just the last two commits are related to this change.

Fix docker

---

config/use.go
executor/executor.go
storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
storage/backend/ceph/mountscan.go
storage/driver.go
systemtests/battery_test.go
systemtests/util_test.go
volmaster/daemon.go

This incorporates many changes that improve the stability of volmaster create operations, which was failing in a lot of scenarios on slower machines.
PTAL @mapuri @unclejack, this is a big change so please review carefully.
closes #121 
closes #122

Fixup storage drivers

---

config/use.go
executor/executor.go
storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
storage/backend/ceph/mountscan.go
storage/driver.go
systemtests/battery_test.go
systemtests/integrated_test.go
systemtests/util_test.go
systemtests/volcli_test.go
systemtests/volplugin_test.go
systemtests/volume_test.go
volmaster/daemon.go

Relies on #127, so review that first
This changes the debian image previously used for many tests in the systemtest suite. It improves test runtime by around a minute.

Use alpine

---

storage/backend/ceph/internals.go
vagrant_variables.yml
volmaster/daemon.go
volplugin/utils.go

the ceph driver `mapImage` call was doing too much and causing trouble.

Fix mapimage

---

executor/executor.go
storage/backend/ceph/ceph.go
storage/backend/ceph/ceph_test.go
storage/backend/ceph/internals.go
storage/backend/ceph/mountscan.go
storage/driver.go
volmaster/daemon.go
volmaster/volmaster/cli.go
volmaster/volume.go
volplugin/volplugin.go
volplugin/volplugin/cli.go
volsupervisor/daemon.go
volsupervisor/schedule_utils.go
volsupervisor/snapshots.go
volsupervisor/volsupervisor/cli.go

storage,volmaster,volsupervisor: add timeout

---

Makefile
Vagrantfile
ansible/roles/docker/defaults/main.yml
ansible/roles/docker/tasks/main.yml

Another ansible upgrade that supports @DivyaVavili's docker version patches.
Will merge this as soon as it passes because it's already been validated elsewhere.

Upgrade ansible

---

systemtests/battery_test.go
systemtests/volplugin_test.go

Several patches to improve performance for systemtests.

Improve test runtime

---

volcli/volcli.go
volcli/volcli_test.go

This change:
- improves the argument count related error string to be more explicit
- adds two List clis where the argument count check was missing to make it consistent with other places.
/cc @erikh @unclejack

improve volcli errors

---

volplugin/volplugin.go

volplugin: guard against listen errors with a log message

---

volmaster/daemon.go
volmaster/volmaster/cli.go
volsupervisor/daemon.go
volsupervisor/schedule_utils.go
volsupervisor/snapshots.go

Fixes #132 
This patch implements daemon-wide structs for use by the services, to keep globals and so on. it cleans up the code a little.

Daemon structs

---

config/config.go
config/volume_test.go

config: clean up units handling, add another test for 1GB to test powers of 1024 are being used.

---

README.md
vagrant_variables.yml

This increases the RAM amount to better accommodate ceph and netplugin.
RIP laptops.

Increase ram

---

Makefile
config/global.go
config/global_test.go
systemtests/testdata/global1.json
systemtests/testdata/global2.json
systemtests/util_test.go
systemtests/volmaster_test.go
systemtests/volplugin_test.go
volcli/commands.go
volcli/volcli.go
volmaster/daemon.go
volmaster/volmaster/cli.go
volplugin/handlers.go
volplugin/utils.go
volplugin/volplugin.go
volplugin/volplugin/cli.go

closes #80.
Note that there are also two additional patches. They improve reliability throughout the system; were discovered while making the global config patch.

Global configuration

---

Makefile
config/global.go
config/global_test.go
info/debug.go
systemtests/testdata/global1.json
systemtests/testdata/global2.json
systemtests/util_test.go
systemtests/volmaster_test.go
systemtests/volplugin_test.go
volcli/commands.go
volcli/volcli.go
volmaster/daemon.go
volmaster/volmaster/cli.go
volplugin/handlers.go
volplugin/utils.go
volplugin/volplugin.go
volplugin/volplugin/cli.go
volsupervisor/daemon.go

This PR is based on #138 and that needs to be merged first.
This introduces a new info package. The new info package enables volplugin, volmaster and volsupervisor to print some debugging info when receiving SIGUSR1.

Debug info

---

Makefile
Vagrantfile
storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
systemtests/battery_test.go
volplugin/handlers.go

Several commits related to improving test reliability and flexibility

Test improvements

---

systemtests/volplugin_test.go
volplugin/volplugin.go

volplugin,systemtests: cleanup socket on shutdown

---

Makefile

Makefile: set provider for `vagrant up` if $PROVIDER is set

---

systemtests/util_test.go
volsupervisor/daemon.go
volsupervisor/snapshots.go
volsupervisor/volsupervisor/cli.go

Volsupervisor: Use globals

---

config/config_test.go
config/use.go
config/use_test.go
lock/client/client.go
lock/lock.go
systemtests/volcli_test.go
systemtests/volmaster_test.go
systemtests/volplugin_test.go
volcli/volcli.go
volmaster/daemon.go
volmaster/utils.go
volplugin/handlers.go
volplugin/utils.go
volplugin/volplugin.go

This isolates the code from volplugin that communicates with the volmaster for clarity and later refactoring purposes.

Locking client + volplugin cleanup

---

lock/lock.go
lock/lock_test.go
lock/policy.json
volmaster/daemon.go

Introduces tests for the lock package

Lock tests

---

Makefile

update godeps in make CI target

---

systemtests/volcli_test.go

@erikh this is just the test for #181 
Somehow for me the test succeeds, so wanted to get your review once in case I am missing something wrt reproduction. In any case having this test seems like good.

systemtest for policy update

---

Godeps/Godeps.json
config/merge.go
config/volume.go
info/debug.go
lock/client/client.go
storage/backend/backends.go
storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
storage/backend/ceph/mountscan.go
storage/backend/ceph/util.go
vendor/github.com/contiv/errored/.travis.yml
vendor/github.com/contiv/errored/errored.go
volcli/volcli.go
volcli/volcli_test.go
volmaster/daemon.go
volmaster/volume.go
volplugin/handlers.go
volplugin/utils.go

This uses the new github.com/contiv/errored package. It will be implemented a little more hardy once I make some modifications to both ends, but this is a good enough approach for now.

Use errored

---

README.md

README.md: refactor header and update with goreportcard status :D

---

systemtests/volmaster_test.go

systemtests: fix "no global configuration" heisenbug in test

---

Makefile

Makefile: remove godep

---

config/policy.go
config/policy_test.go
config/volume.go
config/volume_test.go
lock/policy.json
storage/backend/ceph/ceph_test.go
systemtests/testdata/ceph/fastsnap.json
systemtests/testdata/ceph/fs.json
systemtests/testdata/ceph/nosnap.json
systemtests/testdata/ceph/policy1.json
systemtests/testdata/ceph/policy2.json
systemtests/testdata/ceph/testdriver.json
systemtests/testdata/ceph/testpool.json
systemtests/testdata/test/policy1.json
systemtests/testdata/test/policy2.json
systemtests/testdata/test/testdriver.json
systemtests/volcli_test.go
volmaster/daemon.go
volmaster/volume.go
volplugin/handlers.go
volplugin/utils.go
volsupervisor/loop.go

*: split policy drivers for end-user

---

storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
systemtests/battery_test.go

storage/backend/ceph: better resiliency for mounting code

---

config/config.go
config/volume.go
systemtests/volsupervisor_test.go
volcli/commands.go
volcli/volcli.go
volsupervisor/loop.go
volsupervisor/volsupervisor.go
volsupervisor/watches.go

systemtests,volcli,config,volsupervisor: perform snapshots based on a file written to etcd.

---

Makefile

Will be merging after CI passes

Makefile: cleanups/speedups/fixes

---

systemtests/volsupervisor_test.go
volplugin/handlers.go

volplugin: fix a panic due to a missing error check in getPath()

---

Makefile

Makefile: fix make start and make demo targets to run the applications

---

config/volume.go
config/volume_test.go
storage/backend/ceph/ceph.go
storage/backend/nfs/nfs.go
storage/backend/null/null.go
storage/backend/test/test.go
storage/driver.go
storage/driver_test.go

config,storage: support capability validation for driver options, and conversion to driver options from volumes.

---

Makefile

Makefile: supply TESTRUN to limit unit testing by function name regex

---

build/scripts/systemtests.sh

build/scripts/systemtests.sh: remove last traces of godep

---

Makefile
Vagrantfile
vagrant_variables.yml

This fixes a number of makefile and vagrantfile problems.
Thanks to @dseevr for testing.

Fix release

---

README.md

README.md: corrected all references to old tenant system

---

ansible/roles/base/tasks/redhat_tasks.yml
ansible/roles/contiv_cluster/defaults/main.yml
ansible/roles/contiv_network/defaults/main.yml
ansible/roles/contiv_network/tasks/ovs.yml
ansible/roles/contiv_storage/defaults/main.yml
ansible/roles/docker/tasks/main.yml
ansible/roles/docker/tasks/redhat_install_tasks.yml
ansible/roles/docker/tasks/ubuntu_install_tasks.yml

This brings in the latest changes from contiv/ansible.

Vendor ansible

---

volmaster/daemon.go

volmaster: correct an issue where a 500 would be sent in the event a 404 should be sent.

---

CONTRIBUTING.md
README.md

CONTRIBUTING.md,README.md: clean up a few nits

---

Makefile
systemtests/util_test.go
systemtests/volcli_test.go
volcli/commands.go
volcli/volcli.go
volmaster/daemon.go
volplugin/handlers.go
volplugin/utils.go

volmaster,volplugin: make routes more consistent

---

volcli/volcli.go
volmaster/daemon.go

Makes changes needed for #229.

more changes for the routes

---

config/policy.go
config/policy_test.go
volcli/volcli.go

This PR changes the REST api for the policy listing to send an array of complete policies.

config,volcli,volmaster: send full policy JSON

---

Godeps/Godeps.json
config/config.go
config/global.go
config/policy.go
config/use.go
config/volume.go
config/volume_test.go
errors/errors.go
errors/utils.go
storage/backend/ceph/ceph.go
storage/backend/ceph/internals.go
vendor/github.com/contiv/errored/README.md
vendor/github.com/contiv/errored/errored.go
volmaster/daemon.go
volmaster/utils.go
volmaster/volume.go
volplugin/handlers.go
volplugin/init.go
volplugin/utils.go

This drastically improves the errors that volcil, volplugin and volmaster return. Other modifications will come later, but the pattern and the errors are defined and integrated in the worst pain points.
/cc @jainvipin 
This builds on the same host mount patch, so please review that first.
Closes #182

Better errors

---

build/release-materials/RELEASE.md

build/release-materials: Release notes template

---

Makefile

@mapuri need your review on this one

Makefile: fix release target for releasing specific versions

---

Makefile
contrib/init/sysvrc/volmaster
contrib/init/sysvrc/volplugin
contrib/init/sysvrc/volsupervisor

Init scripts

---

README.md

README.md: update a few sections based on what we support now. :)

---

Makefile

This reverts commit 8be610804e458dea5be9bff6e61bb1c49c154bf5.
I reverted it because it worked for cutting the tarball but does not work for anything else, including breaking the nightly builds.
This will fix the nightlies in the interim while I work on a longer-term solution for releases.

Revert "Makefile: fix release target for releasing specific versions"

---

Vagrantfile

Vagrantfile: support environment variables to forward UI components

---

README.md

README.md: fix go report card link

---

apiserver/daemon.go
systemtests/volcli_test.go
volcli/commands.go
volcli/volcli.go

This implements changes described in #307.
The `-f` flag isn't implemented yet. This is WIP.

volcli,volmaster: implement flags

---

README.md

README.md: update README to reflect new docs site.

---

api/api_test.go
config/policy_test.go
config/volume.go
config/volume_test.go
errors/errors.go
systemtests/volcli_test.go

Use lock nfs

---

Makefile
systemtests/integrated_test.go

systemtests: fix a missing err check caught by ineffassign

---

Vagrantfile
ansible/roles/gluster/defaults/main.yml
ansible/roles/gluster/tasks/install_gluster.yml
ansible/roles/gluster/tasks/main.yml
ansible/roles/gluster/templates/peers.sh.j2
ansible/site.yml

This implements glusterfs installation, I chose to do this early to break the changes into smaller parts.
This is just the ansible and Vagrant changes to install glusterfs. There is no code to drive it yet.

Glusterfs installation

---

Makefile
storage/backend/ceph/internals.go

https://github.com/fzipp/gocyclo is a program to determine the cyclomatic complexity of functions, e.g. if they use too many control statements, and more points are added for inner statements.
This helps keep the code tidy by forcing everyone to use small functions and avoid unnecessarily complicating things. I think it will be a good fit for this project and is a part of the go report card so it directly impacts the front page of our project.
Also included is a single fix for one of the problems. You can run `gocyclo-host` to see the rest of them.

Gocyclo + 1 fix

---

systemtests/battery_test.go
systemtests/volplugin_test.go
volplugin/handlers.go
volplugin/init.go

volplugin, systemtests: Incorporated mount locks

---

ansible/roles/base/tasks/redhat_tasks.yml
ansible/roles/contiv_cluster/defaults/main.yml
ansible/roles/contiv_cluster/tasks/cleanup.yml
ansible/roles/contiv_cluster/tasks/main.yml
ansible/roles/contiv_network/defaults/main.yml
ansible/roles/contiv_network/tasks/aci_tasks.yml
ansible/roles/contiv_network/templates/aci_gw.j2
ansible/roles/contiv_storage/defaults/main.yml
ansible/roles/docker/defaults/main.yml
ansible/roles/docker/tasks/main.yml
ansible/roles/etcd/defaults/main.yml
ansible/roles/etcd/tasks/main.yml
ansible/roles/etcd/templates/etcd.j2
ansible/roles/test/defaults/main.yml
ansible/roles/test/tasks/redhat_tasks.yml
ansible/roles/test/tasks/ubuntu_tasks.yml

this pulls in the fixes done in https://github.com/contiv/ansible/pull/245 along with other recent updates in the ansible repo
/cc @erikh @dseevr

ansible: vendor recent fixes

---

Godeps/Godeps.json
vendor/github.com/contiv/errored/errored.go

Godeps,vendor: upgrade contiv/errored

---

api/api.go
api/docker/docker.go
storage/utils.go
storage/utils_test.go
volplugin/handlers.go
volplugin/utils.go
volplugin/volplugin.go

Mostly removing and moving around a bit of code. No real logic changes.

api/docker,volplugin: new api/docker package for storing docker api top-level handlers.

---

storage/utils_test.go

storage/utils_test.go: simplified code using gofmt

---

README.md

README.md: clean up and simplify use instructions

---

Vagrantfile

Vagrantfile: support vagrant 1.8.5 (and VBox 5.1 by side-effect)

---

config/schema.go
config/validation_test.go

Unit test for all the functions in config/validation.go

Unit-test for JSON validation

---

config/validation.go

config: remove another noisy log message

---

api/impl/docker/docker_test.go

I'll be adding these incrementally as I get time. PTAL

api: implement docker API endpoint unit tests.

---

config/volume.go
storage/mountscan/mountscan.go
systemtests/integrated_test.go
systemtests/testdata/ceph/snaplockedvol.json
systemtests/volsupervisor_test.go
volsupervisor/loop.go

fixes #396 
Signed-off-by: Yuva Shankar <yuva.shankar29@gmail.com>

volsupervisor, config, systemtests: Snapshot only volumes in use

---

volmigrate/backend/backend.go
volmigrate/backend/etcd2/etcd2.go

volmigrate: fix golint and misspell errors flagged by Go Report Card

---

storage/mountscan/mountscan.go

Fixes go report card misspell issue.
Signed-off-by: Yuva Shankar <yuva.shankar29@gmail.com>

storage: fix misspell

---

Makefile

Makefile: connwait before global upload

---

db/constants.go
db/create.go
db/db.go
db/global.go
db/impl/etcd/client.go
db/impl/etcd/dump.go
db/jsonio/jsonreader.go
db/policy.go
db/runtime.go
db/schema.go
db/structs.go
db/test/entities_test.go
db/test/entity_test.go
db/test/etcd_test.go
db/test/global_test.go
db/test/policy_test.go
db/test/volume_test.go
db/validate_json.go
db/volume.go
errors/errors.go

This new implementation is unfinished and contains several known issues (See
below). This implementation contains a new architecture which implements a
visitor model where the visitor (the Entity) fully contains the information to
be persisted to disk, where the processor (the Client) is responsible for
processing the object into a format which is capable to be written to the k/v
store.
This abstraction is necessary for Consul support.
Known issues (will be resolved in v2):
* Hooks calls return closures which are very expensive and generated each time
Hooks is called.
* RuntimeOptions are not capable of being watched because the keyspace is not
sent to the object, so the volume cannot be located.
**NOTE**: I'm calling executive veto on major design changes. This is the design. Let's focus …

New DB API Part #1 (See below)

---

db/volume.go

master is broken, this patch fixes it.
c25c97e9245784c7426b08c355e4a152d86415cc removed the backend.NewDriver call which this code relied on, and they both got merged today.

db/volume.go: fixup new API according in the wake of c25c97e

---

Makefile
build/release-materials/build-release.sh
build/release-materials/release.sh

This doesn't need to pass tests, just for releasing new versions.

Makefile,build/release-materials: initial release generation tooling.

---

apiserver/daemon.go

apiserver/daemon.go: remove unused code/endpoints in API service.

---

api/handlers.go
apiserver/daemon.go
build/scripts/checks.sh
merge/casts.go
merge/merge.go
storage/backend/ceph/ceph.go
storage/backend/nfs/nfs.go

errcheck was removed because it was just too much atm. I will address this later.
Anything `> 15` on gocyclo was resolved. PTAL.

integrate gocyclo

---

Dockerfile
Dockerfile.autorun
build/release-materials/build-release.sh
build/release-materials/release.sh
build/scripts/autorun-bootstrap.sh

Dockerfile,Dockerfile.autorun,build: fixup release materials for v0.3.0

---

db/db.go
db/global.go
db/impl/etcd/client.go
db/policy.go
db/runtime.go
db/test/entity_test.go
db/test/runtime_test.go
db/test/volume_test.go
db/volume.go

This implements the fixes from the last review and makes it ready to integrate, which will be done in the next patch. PTAL.

DB API part 2

---

api/handlers.go
config/use.go
config/use_test.go
config/volume.go
lock/lock.go
systemtests/init_test.go
systemtests/testdata/ceph/fastsnap.json
systemtests/util_test.go
systemtests/volsupervisor_test.go
volsupervisor/loop.go
volsupervisor/volsupervisor.go
volsupervisor/watches.go

This corrects a number of issues with snapshot behavior in volsupervisor.
This is breaking most of the test runs right now so let's get this reviewed today please @yuva29 @dseevr.

Fix volsupervisor restart

---

vagrant_variables.yml

vagrant_variables.yml: revert to box 0.6.0

---

vagrant_variables.yml

vagrant_variables.yml: Upgrade contiv/centos72 version

---

db/test/etcd_test.go
storage/backend/nfs/nfs.go
systemtests/integrated_test.go
systemtests/volsupervisor_test.go
watch/watch.go

This fixes all the issues which the new version of ineffassign is complaining about.

*: fix assignments to make the new version of ineffassign happy
